project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    embed-resources: true
  acs-pdf:
    mermaid:
      theme: neutral
    notebook-links: false
    fig-pos: H
