project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  pdf:
    mermaid:
      theme: neutral
    notebook-links: false
    fig-pos: H
