site_name: SCAttack
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets
nav:
  - 'index.md'
  - 'reference.md'
  - Report: 'report.html'
